version: '1'

services:
  db-prenotazione:
    image: postgres:alpine
    container_name: db-prenotazione
    ports:
      - "5430:5430"
    expose:
      - "5430"
    network_mode: bridge
    environment:
      POSTGRES_DB: dbRicerca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: -p 5430
  microservizi_prenotazione:
    image: pievit/microservizi-prenotazione
    network_mode: bridge
    stdin_open: true
    tty: true
    build:
      context: .
    container_name: microservizi-prenotazione
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.0.7:5430/dbRicerca
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API-GATEWAY-HOST: 172.17.0.5:8080
      RABBITMQ_HOST: 172.17.0.6
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "8082:8080"
    depends_on:
      - db-prenotazione